// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0QjC5TAy-ia1AzLLaaPLL53gcmLH1TbM',
    appId: '1:63042198526:web:842726098633f5e4977eaf',
    messagingSenderId: '63042198526',
    projectId: 'smartoryza',
    authDomain: 'smartoryza.firebaseapp.com',
    databaseURL: 'https://smartoryza-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartoryza.firebasestorage.app',
    measurementId: 'G-3RFX7P8HMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO3BwQuDZlF5xzOovi3eFvHaj_AByZtns',
    appId: '1:63042198526:android:a8307fda87fdd675977eaf',
    messagingSenderId: '63042198526',
    projectId: 'smartoryza',
    databaseURL: 'https://smartoryza-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartoryza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPMPBRyuywyvPAfqkFtbnEKzVWyWa8SB8',
    appId: '1:63042198526:ios:641297249d57c4ab977eaf',
    messagingSenderId: '63042198526',
    projectId: 'smartoryza',
    databaseURL: 'https://smartoryza-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartoryza.firebasestorage.app',
    iosBundleId: 'com.example.oryzaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPMPBRyuywyvPAfqkFtbnEKzVWyWa8SB8',
    appId: '1:63042198526:ios:641297249d57c4ab977eaf',
    messagingSenderId: '63042198526',
    projectId: 'smartoryza',
    databaseURL: 'https://smartoryza-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartoryza.firebasestorage.app',
    iosBundleId: 'com.example.oryzaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0QjC5TAy-ia1AzLLaaPLL53gcmLH1TbM',
    appId: '1:63042198526:web:842726098633f5e4977eaf',
    messagingSenderId: '63042198526',
    projectId: 'smartoryza',
    authDomain: 'smartoryza.firebaseapp.com',
    databaseURL: 'https://smartoryza-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartoryza.firebasestorage.app',
    measurementId: 'G-3RFX7P8HMN',
  );

}